/* ============================================================
   EXERCISE MEDIA — passaggi di esecuzione (IT) dal dataset esercizi
   (uso educativo/non commerciale). GIF in assets/gifs/<key>.gif
   ============================================================ */
const EXERCISE_STEPS = {
  legpress: ["Regolare il sedile e la pedana della macchina da slitta in una posizione comoda.", "Sedersi sulla macchina da slitta con la schiena contro lo schienale e i piedi alla larghezza delle spalle sulla pedana.", "Afferrare le maniglie ai lati del sedile per garantire stabilità.", "Allontanare la pedana dal corpo estendendo le gambe e mantenendo i talloni sulla pedana.", "Continua a spingere finché le gambe non sono quasi completamente estese, ma senza bloccare le ginocchia.", "Fare una pausa per un momento nella parte superiore del movimento, quindi abbassare lentamente la pedana verso il corpo piegando le ginocchia.", "Ripetere per il numero di ripetizioni desiderato."],
  legext: ["Regola l'altezza del sedile e lo schienale della macchina per adattarli al tuo corpo.", "Sedersi sulla macchina con la schiena appoggiata allo schienale e i piedi sul poggiapiedi.", "Afferrare le maniglie o le barre laterali per garantire stabilità.", "Estendi le gambe in avanti raddrizzando le ginocchia, sollevando il peso.", "Fermati per un momento in alto, quindi abbassa lentamente il peso nella posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  legcurl: ["Regola la macchina per adattarla al tuo corpo e seleziona il peso desiderato.", "Sdraiati a faccia in giù sulla macchina con le gambe dritte e i talloni contro la leva imbottita.", "Afferrare le maniglie o i lati della macchina per mantenerla stabile.", "Mantenendo ferma la parte superiore del corpo, espira e piega le gambe il più possibile senza sollevare i fianchi dal cuscino.", "Mantieni la posizione contratta per una breve pausa mentre contrai i muscoli posteriori della coscia.", "Inspira e abbassa lentamente la leva nella posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  hipthrust: ["Inizia sdraiandoti sulla schiena a terra con le ginocchia piegate e i piedi appoggiati sul pavimento.", "Posiziona un bilanciere sui fianchi, tenendolo saldamente con entrambe le mani.", "Coinvolgi i glutei e i muscoli centrali, quindi solleva i fianchi da terra finché il tuo corpo non forma una linea retta dalle ginocchia alle spalle.", "Fermati un attimo in alto, contraendo i glutei.", "Abbassa lentamente i fianchi fino alla posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  calf: ["Stai con i piedi a larghezza delle spalle e posiziona una barra sulla parte superiore della schiena.", "Alza i talloni da terra il più in alto possibile, usando solo le dita dei piedi.", "Fermati un attimo in cima, poi abbassa lentamente i talloni fino alla posizione di partenza.", "Ripeti per il numero desiderato di ripetizioni."],
  abductor: ["Regola l'altezza del sedile in modo che le ginocchia formino un angolo di 90 gradi.", "Sedersi sulla macchina con la schiena appoggiata allo schienale e i piedi sulle pedane.", "Metti le mani sulle maniglie laterali per stabilità.", "Coinvolgi i tuoi abduttori e allarga lentamente le gambe, lontano dalla linea mediana del tuo corpo.", "Fermati un attimo alla fine del movimento, poi riporta lentamente le gambe alla posizione di partenza.", "Ripetere per il numero di ripetizioni desiderato."],
  chestpress: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata al cuscino.", "Afferrare le maniglie con una presa prona e posizionare i gomiti con un angolo di 90 gradi.", "Spingi le maniglie in avanti finché le braccia non sono completamente distese, espirando durante il movimento.", "Fai una breve pausa alla fine del movimento, quindi ritorna lentamente alla posizione di partenza, inspirando mentre lo fai.", "Ripetere per il numero di ripetizioni desiderato."],
  chestfly: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata al cuscino.", "Afferrare le maniglie con presa prona e tenere i gomiti leggermente piegati.", "Espira e spingi le maniglie in avanti, unendole davanti al petto.", "Fai una pausa per un momento, contraendo i muscoli del torace.", "Inspira e ritorna lentamente alla posizione di partenza, permettendo ai muscoli del torace di allungarsi.", "Ripetere per il numero di ripetizioni desiderato."],
  shoulderpress: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata allo schienale.", "Afferrare le maniglie con una presa prona e posizionare le mani all'altezza delle spalle.", "Spingere le maniglie verso l'alto finché le braccia non sono completamente distese, ma non bloccare i gomiti.", "Fermati per un momento in alto, quindi abbassa lentamente le maniglie fino alla posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  lateral: ["Stai in piedi con i piedi alla larghezza delle spalle e tieni un manubrio in ogni mano, palmi rivolti verso il corpo.", "Tieni la schiena dritta e attiva il core.", "Alza le braccia ai lati finché non sono parallele al pavimento, mantenendo una leggera piega dei gomiti.", "Fermati un attimo in cima, poi abbassa lentamente le braccia fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  tricipiti: ["Attacca una barra dritta a una macchina a cavo a carrucole alta.", "Stai rivolto verso la macchina con i piedi a larghezza delle spalle e con una leggera piega delle ginocchia.", "Afferra la barra con una presa sopra la mano, mani a larghezza delle spalle.", "Tieni i gomiti vicini ai fianchi e le braccia superiori ferme.", "Espira e spingi la barra verso il basso finché i gomiti non sono completamente estesi.", "Fermati un attimo, poi inspira e riporta lentamente la barra alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  frenchpress: ["Sdraiati disteso su una panchina con un manubrio in ogni mano, i palmi uno verso l'altro.", "Allunga le braccia dritte sul petto, tenendo i gomiti vicini al corpo.", "Abbassa i manubri verso la fronte, piegando i gomiti.", "Fermati un attimo, poi rialza le braccia fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  latmachine: ["Siediti di fronte alla lat machine con i piedi appoggiati a terra e le ginocchia sotto i rulli.", "Afferra la barra con una presa prona, leggermente più larga della larghezza delle spalle.", "Inclinati leggermente all'indietro e tieni il petto alto, mantenendo un leggero arco lombare.", "Tira la barra verso il petto, guidando con i gomiti e stringendo le scapole.", "Fermati un attimo in basso, poi riporta lentamente la barra alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  pulley: ["Siediti sulla macchina per il rematore con i piedi appoggiati sulle pedane e le ginocchia leggermente piegate.", "Afferra le maniglie con una presa sopra la mano, tenendo la schiena dritta e le spalle rilassate.", "Tira le maniglie verso il corpo, stringendo le scapole insieme.", "Fermati un attimo al picco del movimento, poi rilasci lentamente le maniglie alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  reversefly: ["Regola l'altezza del sedile e posizionati sulla macchina con il petto contro l'imbottitura e i piedi appoggiati sul pavimento.", "Afferrare le maniglie con una presa prona e tenere le braccia leggermente piegate.", "Espira e stringi insieme le scapole mentre tiri le maniglie indietro e verso l'esterno, lontano dal corpo.", "Fermati per un momento al picco della contrazione, quindi inspira e ritorna lentamente alla posizione di partenza.", "Ripetere per il numero di ripetizioni desiderato."],
  curl: ["Impugna il bilanciere EZ nella parte curva interna, presa supinata (palmi verso l'alto).", "Stai dritto, braccia distese, gomiti fermi ai fianchi per tutta la serie.", "Espira e solleva il bilanciere controllando il movimento, fino all'altezza del petto.", "Mantieni la contrazione per una breve pausa stringendo i bicipiti.", "Scendi lento fino a braccia distese — non rimbalzare in basso.", "La presa EZ riduce lo stress sul polso rispetto al bilanciere dritto."],
  hammer: ["Siediti su una panchina con un manubrio in ogni mano, i palmi rivolti verso il busto e le braccia distese verso il basso.", "Tieni la schiena dritta e i gomiti vicini al busto.", "Espira e arrotola il manubrio della mano destra verso la spalla, mantenendo fermo il braccio superiore.", "Continua ad alzare il manubrio finché i bicipiti non sono completamente contratti e il manubrio non è all'altezza delle spalle.", "Fermati un attimo, poi inspira e abbassa lentamente il manubrio fino alla posizione iniziale.", "Ripeti il movimento con il braccio sinistro.", "Continuare ad alternare le braccia per il numero desiderato di ripetizioni."],
  facepull: ["Fissa una maniglia di staffa a una puleggia a cavo bassa e mettiti rivolto verso la macchina.", "Afferra il manico con la mano sinistra e fai un passo indietro con il piede destro, posizionando il corpo con un leggero angolo.", "Flette leggermente le ginocchia e incurva in avanti sui fianchi, mantenendo la schiena dritta e il core attivo.", "Con il braccio sinistro teso e il palmo rivolto verso il basso, tira il manico verso il petto ritirando la scapola.", "Fermati un attimo all'inizio del movimento, stringendo la scapola.", "Rilascia lentamente la maniglia alla posizione iniziale e ripeti per il numero desiderato di ripetizioni.", "Cambia lato e ripeti l'esercizio con il braccio destro."],
  plank: ["Inizia in una posizione di plancia alta con le mani direttamente sotto le spalle e il corpo in linea retta dalla testa ai piedi.", "Coinvolgi il core e i glutei per mantenere una posizione stabile.", "Ruota il busto verso destra, sollevando il braccio destro ed estendendolo verso il soffitto.", "Mantieni i fianchi e le gambe stabili mentre giri.", "Mantieni la posizione per un momento, quindi torna alla posizione di partenza.", "Ripeti la torsione sul lato sinistro.", "Continua ad alternare i lati per il numero di ripetizioni desiderato."],
  crunch: ["Attacca una maniglia di corda a una carrucola alta e inginocchiati rivolto di spalle alla macchina.", "Tieni il manico della corda con entrambe le mani e posizionalo dietro la testa, tenendo i gomiti ai lati.", "Tieni i fianchi fermi, fletti la vita e schiaccia il busto verso le cosce.", "Fermati un attimo in fondo, poi torna lentamente alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
};
